#!/bin/bash
set -e

. /usr/share/debconf/confmodule

chown -R vc-wifitracking:vc-wifitracking /opt/vc-wifitracking

chmod 750 /opt/vc-wifitracking
chmod 750 /opt/vc-wifitracking/app.py

# Write the selected interface to the config file
db_get vc-wifitracker/interface
INTERFACE="$RET"
sed -i "s/^INTERFACE=.*/INTERFACE=${INTERFACE}/" /etc/default/vc-wifitracking

systemctl daemon-reload
systemctl enable vc-wifitracking.service

exit 0
