#!/bin/bash
set -e

chown -R vc-wifitracking:vc-wifitracking /opt/vc-wifitracking
chown root:root /opt/vc-wifitracking/wifi_mode_manager.sh

chmod 750 /opt/vc-wifitracking
chmod 750 /opt/vc-wifitracking/app.py
chmod 700 /opt/vc-wifitracking/wifi_mode_manager.sh

systemctl daemon-reload
systemctl enable vc-wifitracking.service

exit 0
