#!/bin/bash
set -e

chown -R vc-wifitracking:vc-wifitracking /opt/vc-wifitracking

chmod 750 /opt/vc-wifitracking
chmod 750 /opt/vc-wifitracking/app.py

systemctl daemon-reload
systemctl enable vc-wifitracking.service

exit 0
